version: '3.5'

services:
  postgres:
    container_name: postgres_15_otus_container
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - dvd_rental:/tmp

networks:
  postgres:
    driver: bridge

volumes:
  dvd_rental:
    driver: local
    driver_opts:
      type: none
      device: //c/tmp
      o: bind
