version: '3.5'

services:
  postgres:
    container_name: postgres_15_otus_container
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
    volumes:
      - .././script/hw_triggers.sql:/docker-entrypoint-initdb.d/hw_triggers.sql
      - .././script/my_trigger.sql:/docker-entrypoint-initdb.d/my_trigger.sql

networks:
  postgres:
    driver: bridge