version: '3.5'

services:
  postgres:
    container_name: postgres_14_otus_container
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
      TZ: "Europe/Moscow"
      PGTZ: "Europe/Moscow"

    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
